In [1]:
import torch

In [2]:
torch.__version__

'2.5.1+cu121'

In [3]:
if torch.cuda.is_available():
    print(f'CUDA is available {torch.cuda.get_device_name(0)}')
else:
    print('CUDA is not available')

CUDA is available Tesla T4


In [4]:
torch.cuda.get_device_properties(0)

_CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40, uuid=1edb007f-9c42-750e-b87f-4e73960e2311, L2_cache_size=4MB)

## **Creating Tensors**

In [5]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.0612, 0.5362, 0.4926],
        [0.9606, 0.6654, 0.8610]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor([[1,2,3],[2,4,6]], dtype=torch.int32)

tensor([[1, 2, 3],
        [2, 4, 6]], dtype=torch.int32)

In [11]:
torch.full((2,2), 6)

tensor([[6, 6],
        [6, 6]])

## **Shapes and Datatypes**

In [12]:
x = torch.tensor([[2,4,8],[1,3,9]])
x.shape

torch.Size([2, 3])

In [13]:
# torch.zeros_like, torch.ones_like, torch.rand_like
torch.empty_like(x)

tensor([[    137586743438864,     137586743438864,                   0],
        [                  0,        197568495616, 7235419174270214779]])

In [14]:
x.to(torch.float32)

tensor([[2., 4., 8.],
        [1., 3., 9.]])

## **Mathematical Operations**

In [18]:
y = torch.tensor([4.6, 2.3, 3.5, 5.4])

In [19]:
torch.round(y)

tensor([5., 2., 4., 5.])

In [20]:
torch.floor(y)

tensor([4., 2., 3., 5.])

In [21]:
torch.ceil(y)

tensor([5., 3., 4., 6.])

In [22]:
torch.clamp(y, min=3, max=5)

tensor([4.6000, 3.0000, 3.5000, 5.0000])

In [23]:
torch.argmin(y)

tensor(1)

In [24]:
torch.argmax(y)

tensor(3)

## **Special Functions**

In [25]:
torch.sigmoid(y)

tensor([0.9900, 0.9089, 0.9707, 0.9955])

In [26]:
torch.tanh(y)

tensor([0.9998, 0.9801, 0.9982, 1.0000])

In [27]:
torch.relu(y)

tensor([4.6000, 2.3000, 3.5000, 5.4000])

In [28]:
# dtype must be float, 0 means columns, 1 means rows
torch.softmax(y, dim=0)

tensor([0.2733, 0.0274, 0.0910, 0.6083])

## **GPU Based Calculations**

In [29]:
a = torch.rand(2,3)
b = a
print("ID - a", id(a))
print("ID - b", id(b))
b = a.clone()
print("ID - a", id(a))
print("ID - b", id(b))

ID - a 137582490472944
ID - b 137582490472944
ID - a 137582490472944
ID - b 137582489728208


In [31]:
x = torch.tensor([[1,1,1],[1,1,1]])
y = torch.tensor([[2,2,2],[2,2,2]])
print("x + y", x.add(y))
print("x", x)
print("y", y)
print("x + y", x.add_(y))
print("x", x)
print("y", y)

x + y tensor([[3, 3, 3],
        [3, 3, 3]])
x tensor([[1, 1, 1],
        [1, 1, 1]])
y tensor([[2, 2, 2],
        [2, 2, 2]])
x + y tensor([[3, 3, 3],
        [3, 3, 3]])
x tensor([[3, 3, 3],
        [3, 3, 3]])
y tensor([[2, 2, 2],
        [2, 2, 2]])


In [32]:
device = torch.device('cuda')

# Create tensors on GPU
torch.tensor([1,2,3], device=device)

# Move tensors to GPU
torch.tensor([1,2,3]).to(device)

tensor([1, 2, 3], device='cuda:0')

## **CPU VS GPU**

In [34]:
import time

size = 10000
matrix_cpu_1 = torch.randn(size, size)
matrix_cpu_2 = torch.randn(size, size)

# Measure Time on CPU
start = time.time()
result_cpu = torch.matmul(matrix_cpu_1, matrix_cpu_2)
end = time.time()
print("CPU Time:", end - start)

matrix_gpu_1 = matrix_cpu_1.to(device)
matrix_gpu_2 = matrix_cpu_2.to(device)

# Measure Time in GPU
start = time.time()
result_gpu = torch.matmul(matrix_gpu_1, matrix_gpu_2)
end = time.time()
print("GPU Time:", end - start)


CPU Time: 16.514270305633545
GPU Time: 0.0013425350189208984


## **NumPY and PyTorch**

In [35]:
import numpy as np

In [36]:
a = torch.tensor([1,2,3])
b = a.numpy()
print(type(b))

<class 'numpy.ndarray'>


In [37]:
a = np.array([1,2,3])
b = torch.from_numpy(a)
print(type(b))

<class 'torch.Tensor'>
